package com.dodo.project.base.admin.dao.system.model;

import com.dodo.project.base.admin.dao.system.model.base.BaseSystemUserNotify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemUserNotify extends BaseSystemUserNotify<SystemUserNotify> {
	public static final SystemUserNotify dao = new SystemUserNotify().dao();
}
