package com.dodo.project.base.admin.dao.system.model;

import com.dodo.project.base.admin.dao.system.model.base.BaseSystemMenuNode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemMenuNode extends BaseSystemMenuNode<SystemMenuNode> {
	public static final SystemMenuNode dao = new SystemMenuNode().dao();
}
