package com.dodo.project.base.admin.dao.system.model;

import com.dodo.project.base.admin.dao.system.model.base.BaseSystemRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemRole extends BaseSystemRole<SystemRole> {
	public static final SystemRole dao = new SystemRole().dao();
}
