package com.dodo.project.base.admin.dao.system.model;

import com.dodo.project.base.admin.dao.system.model.base.BaseSystemLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemLog extends BaseSystemLog<SystemLog> {
	public static final SystemLog dao = new SystemLog().dao();
}
