package com.dodo.project.base.admin.dao.system.model;

import com.dodo.project.base.admin.dao.system.model.base.BaseSystemSubscriptionConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemSubscriptionConfig extends BaseSystemSubscriptionConfig<SystemSubscriptionConfig> {
	public static final SystemSubscriptionConfig dao = new SystemSubscriptionConfig().dao();
}
