package com.dodo.project.base.admin.dao.system.model;

import com.dodo.project.base.admin.dao.system.model.base.BaseSystemConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemConfig extends BaseSystemConfig<SystemConfig> {
	public static final SystemConfig dao = new SystemConfig().dao();
}
